- name: Simple task to launch EC2
  ec2:
    key_name: "{{ Key_name }}"
    region: "{{ Region }}"
    image: "{{ Image }}"
    group: "{{ Group }}"
    wait: yes
    count: 1
    instance_tags:
      Name: "{{ Instance_Name }}"
    instance_type: "{{ Instance_type }}"
  register: ec2_Apigee
- name: Wait for SSH to come up
  wait_for: 
    host={{ item.public_dns_name }} 
    port=22 
    delay=60 
    timeout=320 
    state=started
  with_items: '{{ec2_Apigee.instances}}'
- name: Add new instance to host group
  add_host: name="{{ item.public_ip }}" groupname=Dev_Apigee
  with_items: '{{ec2_Apigee.instances}}'

